mode: qa
preprocessing:
    load: False
    substitle_file: data/AnotherMissOh_Subtitle
    qa_file: data/0529_specific_qa.json
    output_path: data/output/preprocessed.json
    coreference: gold

extraction:
    load: False
    oie: stanford
    frame: frameBERT
    output_path: data/output/extracted.json

background:
    load: True
    input_path: data/background.txt
    output_path: data/output/background_KB.json

graph:
    character_name: data/character.txt
    visualization: False
    package_path: C:/Program Files (x86)/Graphviz2.38/bin/
    graph_path: data/output/graphs
    character: all
    only_use: None
